src/Microsoft.AspNet.SignalR.Client/Transports/ServerSentEventsTransport.cs

If the disconnectToken is tripped before any request was made the _request class variable won't be set in which case OnStartFailed would throw because it tried to call `_request.Abort()`. Adding a null check to prevent the NRE.
Fixes #3376

TrippedOnNull - occasionall NRE in SSE transport

---

build/Build.proj
nuspecs/Microsoft.AspNet.SignalR.Client.nuspec

When a project targeted both net45 and wpa81 or win8 we did not have a subset that could satisfy this. The store websocket transport can only be used if an app/lib targets wpa81 and/or win8 since it is using WinRT APIs. If the app/lib targets any other platform in addition to wpa81/win8 the store websocket cannot be used and therefore we must not install it. Adding wpa81/win8 platforms to the folder containing just the portable version of Microsoft.AspNet.SignalR.Client.dll will do the trick - this folder will be selected if the application targets any other platform in addition to wpa81/win8
Fixes #3393

ForYouTheStoreIsClosed

---

src/Microsoft.AspNet.SignalR.Core/Owin/OwinExtensions.cs

The theory is that tha hangs are caused by a CultureInfo that leaked
from a different AppDomain (see this blog post for more details:
(http://www.zpqrtbnk.net/posts/appdomains-threads-cultureinfos-and-paracetamol).
Unfortunately, I was not however able to reproduce the issue (tried both English
and non-English Windows) but hope it will fix #3414 as indicated in the discussion
and the above blog post.

HopeIsTheOnlyStrategy - fixing hangs when creating Perf Counters

---

src/Microsoft.AspNet.SignalR.Client.UWP/project.json

Fixes #3736 
Verified locally that this works with the UWP client
/cc @muratg @BrennanConroy @moozzyk

move UWP Client JSON.Net dep back to 6.0.4

---

src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.foreverFrame.js

See commit c9200820823395b1b31d3b800938568e496ca2c5 by moozzyk on Aug 13, 2014
foreverFrame was moved to documentElement however stop was still looking for it in the body.  End result was connection was disposed but frame survived causing null reference errors to be thrown.
Fixes #2795

OutOfBodyExperience - removing IFrame from body

---

src/Microsoft.AspNet.SignalR.Client/Transports/TransportHelper.cs

An extraneous call to IHttpClient.Initialize when sending the start requests resets httpClients in the DefaultHttpClient. This may break load balancers and prevent reusing HTTPS connections (SSL negotation will happen twice - once for negotiate and once for start)
More: #3829

Removing extraneous call to IHttpClient.Initialize

---

Microsoft.AspNet.SignalR.sln
src/Microsoft.AspNet.SignalR.Core/Transports/TransportHeartBeat.cs

when a connection hops transports, we don't properly transfer the connection in the perf counters; this change fixes that
fixes #3459

fix #3459 by transferring perf counter values

---

src/Microsoft.AspNet.SignalR.Utils/Commands/GenerateHubProxyCommand.cs

The Signalr.exe utility only scanned for DLL's.  In the case of a self-hosted OWIN process, the hubs are generally part of the EXE.  Added a /exe flag that will search EXE's first, followed by DLL's.

Added EXE support (for OWIN self-hosted SignalR hubs)

---

src/Microsoft.AspNet.SignalR.Redis/Microsoft.AspNet.SignalR.Redis.csproj
src/Microsoft.AspNet.SignalR.Redis/RedisScaleoutConfiguration.cs
src/Microsoft.AspNet.SignalR.Redis/packages.config
tests/Microsoft.AspNet.SignalR.Redis.Tests/RedisMessageBusFacts.cs

- update StackExchange.Redis to 1.1.603 (to include [c7be31](https://github.com/StackExchange/StackExchange.Redis/commit/c7be31107e8e684ba805253b1fdd66a6017f725b))
- parse defaultDatabase from connectionstring
#3714

use default Redis Database from ConnectionString

---

src/Microsoft.AspNet.SignalR.Redis/RedisConnection.cs

_Lua will automatically convert string and number types to the correct format to perform calculations. (...) A notable exception: comparison operators (== ~= < > <= >=) do not coerce their arguments._
Fixes: #3767

Converting strings to numbers for comparison in lua script

---

src/Microsoft.AspNet.SignalR.Client.JS/build.ps1

From AjaxMinifier.exe -?
-term > ensure output ends in semicolon or other valid terminator.
Fixes #3516

Making sure minified script contains trailing semicolon

---

src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js

Unbind the onStart event before disconnected is called. This can cause a large client memory leak when the client is continuously reconnecting. Fix for issue #3793.

Unbind the onStart event

---

src/Microsoft.AspNet.SignalR.Core/Owin/OwinWebSocketHandler.cs
src/Microsoft.AspNet.SignalR.Core/Transports/WebSocketTransport.cs

Previously we would subscribe to webSocketHandler events after starting processing webSocket messages this could lead to missing some events. After the change we would subscribe to webSocketHandler events before we start processing webSocket messages.

Subscribing to events before starting processing webSocket messages

---

src/Microsoft.AspNet.SignalR.Client.NetStandard/Microsoft.AspNet.SignalR.Client.NetStandard.csproj
src/Microsoft.AspNet.SignalR.Client.Portable/Microsoft.AspNet.SignalR.Client.Portable.csproj
src/Microsoft.AspNet.SignalR.Client.Store/Microsoft.AspNet.SignalR.Client.Store.csproj
src/Microsoft.AspNet.SignalR.Client.UWP/Microsoft.AspNet.SignalR.Client.UWP.csproj
src/Microsoft.AspNet.SignalR.Client.WinRT/Microsoft.AspNet.SignalR.Client.WinRT.csproj
src/Microsoft.AspNet.SignalR.Client/Hubs/HubProxy.cs
src/Microsoft.AspNet.SignalR.Client/Microsoft.AspNet.SignalR.Client.csproj
src/Microsoft.AspNet.SignalR.Client45/Microsoft.AspNet.SignalR.Client45.csproj
src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs
src/Microsoft.AspNet.SignalR.Core/Infrastructure/DispatchingTaskCompletionSource.cs
src/Microsoft.AspNet.SignalR.Core/Microsoft.AspNet.SignalR.Core.csproj
src/Microsoft.AspNet.SignalR.Core/TaskAsyncHelper.cs
tests/Microsoft.AspNet.SignalR.FunctionalTests/Client/HubProxyFacts.cs

Fixing an issue where user's code would run a continuation of `HubProxy.Invoke` on a SignalR thread because we were using TaskCompletionSource with default settings. If the user's code blocked it would completely block the receive queue and the user will no longer get any notifications even though the client processes them and add to the queue.  The fix is to dispatch the completion of `HubProxy.Invoke` to a different thread (note that we can't use `TaskCreationOptions.RunContinuationsAsynchronously` because some platforms we compile for do not support this).

Fix for #3895

---

CONTRIBUTING.md

Could not sign in with link provided. Searched for solution online and
found cla.microsoft.com to actually work where I could sign in using my
github account.

Fix: contributor license link was broken.

---

build/Microsoft.AspNet.SignalR.versions.targets

We calculate the 3rd segment of the Assembly File Version using something like: `$"{(Current Year - 2012) + 1}{DateTime.Now.ToString("MMdd")}`. But, `(2018 - 2012) + 1 = 7`, meaning our numbers will be `7MMdd`, which overflows the max of `65535`. So, it's time to rev the "start year" :). This is safe as long as the version number is also incremented at the same time, which was done in #4059, so we're good.

fix version start year in dev

---

build/Microsoft.AspNet.SignalR.versions.targets
samples/Microsoft.AspNet.SignalR.Samples/Scripts/hubs.js
src/Common/CommonVersionInfo.cs
src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.version.js
src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.Core/Scripts/hubs.js

Fixes #4090 
Time for some of the aspnet/SignalR folks to get involved in code reviews :). Here's a nice simple one. This updates all version numbers in SignalR/SignalR to 2.3.0-alpha1. This is needed because we ran out of patch versions in the file version.
Some history:
* .NET binaries have two versions: Assembly Version and File Version (the latter being a Windows concept). This is **in addition** to NuGet Package Version (which is stored as the Assembly "Informational" Version as well)
* Assembly Versions are always `[major].[minor].[patch]` (matching the NuGet Package)
* File Versions are of the form `[major].[minor].[revision].[build]`:
* `[major]` and `[minor]` are set to the same version as the NuGet package. 
* `[build]` is set to a sequence number based on the TeamCity build …

update versions to 2.3.0

---

src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStore.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutSubscription.cs
tests/Microsoft.AspNet.SignalR.Tests/Server/ScaleoutStoreFacts.cs

The `TryAddImpl` method on ScaleoutStore doesn't properly update `_minMappingId`. This is mostly benign except for the one case where `_minMappingId` is used: to detect that a cursor is so far behind that they should just be given all messages when requesting new messages.
Instead of being set to a "Mapping ID", the `_minMappingId` value gets set to a local message ID whenever a fragment is overwritten. This means the value gets corrupted. It was hard to detect this in our tests because they use the same value for both Mapping ID and Local ID, so I changed the tests to have the Mapping IDs start much higher (which is usually the case when deep into a long-running application).
This issue can cause a long-idle connection to end up being frozen out and seeing no new messages because their …

fix issue with ScaleoutStore minMappingId being incorrect

---

src/Microsoft.AspNet.SignalR.Core/PersistentConnection.cs
test/Microsoft.AspNet.SignalR.Tests.Common/TestRequest.cs
test/Microsoft.AspNet.SignalR.Tests.Common/TestResponse.cs
test/Microsoft.AspNet.SignalR.Tests.Common/TestTransport.cs
test/Microsoft.AspNet.SignalR.Tests.Common/TestTransportManager.cs
test/Microsoft.AspNet.SignalR.Tests/PersistentConnectionFacts.cs

The Azure SignalR Service SDK uses it's own custom connection tokens. Currently, make things work, they manually hack up a connection token that will validate correctly when they pass it through their PersistentConnection. This change allows any PersistentConnection to provide custom `connectionToken` validation and parsing logic by overriding the `TryGetConnectionId` method.
cc @vicancy
Fixes #4175

fix #4175 by making TryGetConnectionId virtual

---

src/Microsoft.AspNet.SignalR.Client/Http/DefaultHttpClient.cs
src/Microsoft.AspNet.SignalR.Client/Http/HttpResponseMessageWrapper.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/Http/DefaultHttpClientFacts.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/Http/TestHttpMessageHandler.cs

fixes #4092 by disposing the response on a failure.
TODO:

fix #4092 by disposing the response if it's a failed status code

---

src/Microsoft.AspNet.SignalR.Core/Owin/OwinWebSocketHandler.cs

This PR addresses a very specific issue we're having while running SignalR on top of Asp.Net Core using  `Microsoft.AspNetCore.Owin`.
We're aware this is an unsupported setup and it's part of our migration path going forward.
Running SignalR on Core actually works when addressing 2 separate issues.
The first one is `Microsoft.AspNetCore.Owin` not setting `server.Capabilities[websocket.Version]`, which is easily fixed with some middleware gymnastics.
The second issue is core's owin bridge does not expose a `WebSocketContext` and causes SignalR to fall back to using `OwinWebSocket`. However `OwinWebSocket`'s implementation is incomplete and causes it to fail only moments later when SignalR calls `WebSocket.State`.
Fixing this second issue would be rather involved. Rather we opted to take …

Fix compatibility with Microsoft.AspNetCore.Owin

---

src/Microsoft.AspNet.SignalR.Client/Http/DefaultHttpClient.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/ConnectionFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/HubProxyFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/LongPollingFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/WebSocketFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Microsoft.AspNet.SignalR.FunctionalTests.csproj
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/ConnectionFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/DisconnectFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/FarmFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/PersistentConnectionFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/ReconnectFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/DateFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/GetHubContextFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/HubAuthFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/HubFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/HubProgressFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/SecurityFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Transports/WebSocketFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/MemoryHost.cs

I think I've removed most of the synchronous `Wait` calls from our tests so the thread-pool won't be starved during the test run. This should improve functional test reliability.

Major deflaking

---

src/Directory.Build.props

fixes #4109 by embedding the PDBs in the NuGet packages. See below for the impact on package sizes (all packages measured in Release builds):
| Package | Without (KB) | With (KB) | Increase |
|----------------------------------------------------------------|--------------|-----------|----------|
| Microsoft.AspNet.SignalR.Client| 242.34       | 325.64    | 34%      |
| Microsoft.AspNet.SignalR.Core| 160.60       | 213.52    | 33%      |
| Microsoft.AspNet.SignalR.Redis| 24.31        | 30.01     | 23%      |
| Microsoft.AspNet.SignalR.ServiceBus| 23.96        | 30.43     | 27%      |
| Microsoft.AspNet.SignalR.ServiceBus3| 24.93        | 31.50     | 26%      |
| Microsoft.AspNet.SignalR.SqlServer| 31.46        | 39.54     | 26%      |
| Microsoft.AspNet.SignalR.SystemWeb| 6.12         | …

add pdbs to nuget packages

---

samples/Common/CommonClient.cs
samples/Microsoft.AspNet.SignalR.Client.Samples/Microsoft.AspNet.SignalR.Client.Samples.csproj
samples/Microsoft.AspNet.SignalR.Client.Samples/Program.cs
src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs

fixes #4232
Cleaned up the old #ifdef logic to make sure the WebSocket transport is enabled in the .NET Standard 2.0 build

fix #4232 by enabling WebSocket transport on .NET Standard 2.0

---

samples/Microsoft.AspNet.SignalR.Samples/Hubs/DemoHub/DemoHub.cs
src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.Client/Http/IResponseExtensions.cs
src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs
src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStream.cs
src/Microsoft.AspNet.SignalR.Core/TaskAsyncHelper.cs
src/Microsoft.AspNet.SignalR.SqlServer/DbOperation.cs
src/Microsoft.AspNet.SignalR.Stress/Performance/SimpleEchoHubRun.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/ConnectionFacts.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/HubProxyFacts.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/Infrastructure/TaskQueueFacts.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/TransportFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/HubProxyFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/LongPollingFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/ConnectionFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/PersistentConnectionFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/HubFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Hubs/SecurityFacts.cs
test/Microsoft.AspNet.SignalR.Redis.Tests/RedisMessageBusFacts.cs
test/Microsoft.AspNet.SignalR.Tests/Server/MessageBusFacts.cs
test/Microsoft.AspNet.SignalR.Tests/Server/SubscriptionFacts.cs
test/Microsoft.AspNet.SignalR.Tests/Server/Transports/ForeverTransportFacts.cs
test/Microsoft.AspNet.SignalR.Tests/Server/Transports/LongPollingTransportFacts.cs
test/Microsoft.AspNet.SignalR.Tests/TaskAsyncHelperFacts.cs

fixes #4100
converts calls to TaskCompletionSource.[SetResult|SetException|SetCanceled] to TaskCompletionSource.Try[SetResult|SetException|SetCanceled]
After conversations with @davidfowl, we decided to just put `Try` in everywhere to prevent any case where the exception in #4100 could slip through

fix #4100 by always trying

---

build/dependencies.props
src/Microsoft.AspNet.SignalR.Client/Microsoft.AspNet.SignalR.Client.csproj

This updates only the (new in 2.4.0) `netstandard2.0` target to JSON.NET 11. This is the lowest version of JSON.NET with an explicit `netstandard2.0` target. It also happens to be the latest version :).
Fixes #4170

fix #4170 by updating netstandard2.0 build to JSON.NET 11

---

src/Microsoft.AspNet.SignalR.Client/Resources.Designer.cs
src/Microsoft.AspNet.SignalR.Client/Resources.resx
src/Microsoft.AspNet.SignalR.Client/Transports/TransportHelper.cs
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/Properties/launchSettings.json
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Core/NegotiateFacts.js
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/ConnectionFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/App_Start/Initializer.cs

fixes #4160
This change adds logic to the JS and .NET clients to detect ASP.NET Core servers using the 'availableTransports' property in the negotiate response, which is unique to ASP.NET Core

fix #4160 by detecting ASP.NET Core Servers

---

src/Microsoft.AspNet.SignalR.Core/Messaging/Subscription.cs
src/Microsoft.AspNet.SignalR.Core/Scripts/hubs.js
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.hubs.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Hubs/HubEventHandlerFacts.js

fixes #4213
Previously we used the callback as the key in a JavaScript object. ECMAScript objects are required to have 'String' keys, which means the function is stringified and the string representation is used as the key. The problem is that functions can often have the same string representation. For example, if they are wrapped in something like `bind` or `apply`, the representation is `function() { [native code] }`.
This change switches to use an array and a 'guid' assigned by 'on' as the lookup system. That avoids the problems with stringifying functions. This system of assigning a 'guid' is used by jQuery internally for it's own event lists so it seems like the most appropriate way to handle this.

fix #4213 by tracking callback identity better

---

src/Microsoft.AspNet.SignalR.Core/Messaging/MessageBroker.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/MessageBus.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/Subscription.cs
src/Microsoft.AspNet.SignalR.Core/Transports/ForeverTransport.cs
src/Microsoft.AspNet.SignalR.Core/Transports/LongPollingTransport.cs
src/Microsoft.AspNet.SignalR.Core/Transports/TransportDisconnectBase.cs
test/Microsoft.AspNet.SignalR.Tests/Messaging/MessageBrokerFacts.cs
test/Microsoft.AspNet.SignalR.Tests/Messaging/TestSubscription.cs
test/Microsoft.AspNet.SignalR.Tests/Server/Transports/ForeverTransportFacts.cs
test/Microsoft.AspNet.SignalR.Tests/TestPerformanceCounterManager.cs

Fixes #4126
If OnDisconnected throws or returns a faulted task, we don't dispose the MessageBus subscriptions associated with that connection. This results in the topic and associated messages leaking since nothing is left to dispose them.
This change suppresses the exception that arises in OnDisconnect after logging it so that the rest of the pipeline can carry on.
I haven't yet figured out a good way to test this. I did manual verification that there is indeed a leak in this scenario and that this change resolves the leak. cc @halter73 on this one as well since it's a bit obscure and I'd certainly value another set of SignalR-experienced 👀. It's only WIP because I might try to get a test figured out (though there isn't great existing coverage to base this on AFAICT) and I left some `// …

fix #4126 by suppressing disconnect exception after logging

---

CONTRIBUTING.md

SignalR "Classic"'s contribution guide had really out of date CLA information. The CLA bot is running on this repo but the guide points at a dead link (https://cla2.dotnetfoundation.org) and states (incorrectly) that you need to sign before submitting the PR.
I haven't rewritten the whole guide, but I grabbed the CLA segment from aspnet/Home and copied it here to bring things in line with reality again :)

bring CLA info in-line with reality

---

.vsts-pipelines/builds/ci-official.yml
build/loc/LocalizeDlls.targets
samples/Microsoft.AspNet.SignalR.Samples/Scripts/hubs.js

BEFORE Merging: Check with @Eilon on the "governanceProduct" value.
This PR fixes a build failure in loc, adds a change from a previous bug fix that was missed and enables the Component Governance task to register OSS components to the build.

Fix loc and enable component governance in official build

---

src/Microsoft.AspNet.SignalR/loc/Microsoft.AspNet.SignalR.satellite.nuspec

I've verified that this fixes nuget restore for projects that depend on Microsoft.AspNet.SignalR.$Locale$. "Microsoft.AspNet.SignalR.SystemWeb.en-US" has never existed, so I'm not sure how that got introduced. This should bring us back to parity with 2.3.0.
@davidfowl @muratg 	While this should fix the missing dependency issue, I think we should consider no longer publishing satellite packages unless we have a reasonable way to test it.
The experience just doesn't seem very good. For example, installing Microsoft.AspNet.SignalR.zh-Hans will bring in Microsoft.AspNet.SignalR.SystemWeb.zh-Hans, but it will not bring in Microsoft.AspNet.SignalR.Core.zh-Hans which seems pretty silly for a metapackage. This is because Microsoft.AspNet.SignalR.SystemWeb.zh-Hans depends on …

Fix satellite dependency

---

src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Core/RedirectFacts.js
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/NegotiateFacts.cs

@vicancy This is a follow up to #4300. The main changes are:
1. The user-specified query string is no longer merged with the redirect query string. The redirecting server is expected to reflect the user-specified query string.
2. The connection's URL and query string are now reset to their initial user-specified values when the connection stops instead of retaining their redirected values.
3. The .NET client's "Connection.Url" property no longer matches the redirect value and instead always maintains its initial value.
4. The JS clients "url" property does reflect the redirect value until the client stops, because the public url and related properties are used in various internal places. This is the already-existing behavior, and it does seem worthwhile to untangle it to behave like the …

 Make client redirect logic more similar to the core clients

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js

There is no need to continue when error message is received.

Directly return when Error with received message

---

Directory.Build.props
build/repo.targets

This change links to the 2.3.0 version of LICENSE.txt. That file hasn't changed since 2.3.0. The previous non-official PackageLicenseUrl referenced the "master" branch, but it's generally considered bad practice to link to a living branch. In aspnet/AspNetCore, the PackageLicenseUrl always points to the 2.0.0 version of its LICENSE.txt, so there's precedent.
https://github.com/aspnet/AspNetCore/blob/e7b00a55083a56971e0d340ad2a3d350fec05883/Directory.Build.props#L14
Fixes: #4326

Update package license to be .NET Foundation / Apache

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.hubs.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Hubs/HubEventHandlerFacts.js

Make invalid hub.off() calls from old generated hub proxies work

---

README.md

The existing link points to the archived repo:

update link to asp.net core signalr "repo"

---

src/Microsoft.AspNet.SignalR.Client/Resources.Designer.cs
src/Microsoft.AspNet.SignalR.Client/Resources.resx
src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/TransportFacts.cs

This fixes #4435 
```
02:22:03.0517617 - null - ChangeState(Disconnected, Connecting)
02:22:03.4398446 - PaDbxAX6F1J915s93MztvA4c7d46aa1 - SSE: GET https://notserverlessservice.service.signalr.net/aspnetclient/connect?clientProtocol=2.1&transport=serverSentEvents&connectionData=[{"Name":"ChatSampleHub"}]&connectionToken=PaDbxAX6F1J915s93MztvA4c7d46aa1&asrs_request_id=xEAfJaQDAAA%3D&asrs.op=%2Fsignalr
02:22:03.4807895 - PaDbxAX6F1J915s93MztvA4c7d46aa1 - SSE: OnMessage(Data: {"S":1,"M":[]})
02:22:03.5087902 - PaDbxAX6F1J915s93MztvA4c7d46aa1 - ChangeState(Connecting, Connected)
02:22:03.7990574 - PaDbxAX6F1J915s93MztvA4c7d46aa1 - SSE: OnMessage(Data: {})
```
```
02:23:45.3868953 - null - ChangeState(Disconnected, Connecting)
02:23:45.7129968 - pql9Bwbc_1lu9DJSKUKCpw4c7d46aa1 - WS Connecting …
```

Read TryWebSockets from last negotiate response in .NET client

---

src/Microsoft.AspNet.SignalR.Client/Infrastructure/TransportInitializationHandler.cs
src/Microsoft.AspNet.SignalR.Client/Resources.Designer.cs
src/Microsoft.AspNet.SignalR.Client/Resources.resx
src/Microsoft.AspNet.SignalR.Client/Transports/ClientTransportBase.cs
src/Microsoft.AspNet.SignalR.Client/Transports/LongPollingTransport.cs
src/Microsoft.AspNet.SignalR.Client/Transports/ServerSentEventsTransport.cs
src/Microsoft.AspNet.SignalR.Client/Transports/WebSocketTransport.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/Infrastructure/TransportInitializationHandlerFacts.cs
test/Microsoft.AspNet.SignalR.Client.Tests/Client/Transports/AutoTransportFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/ConnectionFacts.cs

There was a race observed in the .NET client's ServerSentEventsTransport that caused the client to both try to fall back from SSE to long polling, and also reconnect with SSE. The following server logs show the buggy behavior.
UTC time | connection Id | Event | Method | URL
-- | -- | -- | -- | --
2019-12-02T00:21:12.2371847Z | foo | Request End | GET | http://ne-1.service.signalr.net/aspnetclient/connect?clientProtocol=2.1&transport=serverSentEvents&connectionData=[%7B%22Name%22:%22SomeHub%22%7D]&connectionToken=bar&asrs_request_id=baz%3D&asrs.op=%2Fsignalr
2019-12-02T00:21:12.2372764Z | foo | Request Start | POST | http://ne-1.service.signalr.net/aspnetclient/connect?clientProtocol=2.1&transport=longPolling&connectionData=[%7B%22Name%22:%22SomeHub%22%7D]&connectionToken=bar&asrs_request_i …

Fall back or reconnect but not both (.NET client)

---

src/Microsoft.AspNet.SignalR.Core/Transports/TransportDisconnectBase.cs

There are some code paths where Dispose() can be called but not End() despite being subscribed to the bus. One such example is when InitializeResponse() throws and there's no subsequent /abort request.
@davidfowl @anurse

Unsubscribe transport from bus on dispose

---

.vsts-pipelines/builds/ci-official.yml
.vsts-pipelines/builds/ci-public.yml
.vsts-pipelines/templates/signalr-build.yml

@anurse @davidfowl 
@mmitche The [signalr-build.yml template](https://github.com/SignalR/SignalR/blob/cb6c9a91e9771d1bc7748f8ae1823fb29ed81a92/.vsts-pipelines/templates/signalr-build.yml) appears to be pretty outdated and doesn't use arcade's eng/common/templates/jobs/jobs.yml like dotnet/extensions does. Do I need to specify "queue: BuildPool.Server.Amd64.VS2019" like dotnet/extensions does [here](https://github.com/dotnet/extensions/blob/75759edc975749e1a8c4198c0078755a1822eac8/azure-pipelines.yml#L83)?

Change official build pool

---

.vsts-pipelines/builds/ci-official.yml
.vsts-pipelines/builds/ci-public.yml
.vsts-pipelines/templates/signalr-build.yml

This reverts commit db24cd8c8c538c2a776d8f500c9d3241f60e6706.
It looks like you need to use the 'job' instead of 'phase' syntax.

Revert "Change official build pool (#4459)"

---

src/Microsoft.AspNet.SignalR.Core/Transports/TransportHeartBeat.cs

Something that we noticed while analyzing Perfview trace taken during the incident with our service. Perfview showed that there was a lock contention on the `ConcurrentDictionary.Values` property that pointed to `TransportHeartBeat.GetConnections()` method.
`ConcurrentDictionary.Values` would create a snapshot of the dictionary which requires taking global lock of all dictionary buckets. We should not need snapshot behavior here and can use "lock-free" enumeration of the dictionary members.
This is a fix for https://github.com/SignalR/SignalR/issues/4416

Fixed lock contention when querying connections

---

src/Microsoft.AspNet.SignalR.JS/README.md

per the doc issue reported [here](https://github.com/dotnet/aspnetcore/issues/21618), this update makes it more up-front which client customers should use, when their only knowledge of SignalR Is from perusing NPM packages, or who find their way here via OG SignalR docs.

readme updates

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/UnitTests/Connections/ConnectionStateFacts.js
version.props

I'm hoping this fixes #4536.
`markLastMessage` should still run frequently enough to keep `lastMessageAt` up-to-date despite chrome's new timer throttling because `markLastMessage` called by "network response handlers". This means we have to effectively disable our `lastMessageAt` checking logic if keep-alives are disabled.

Update lastMessageAt in markLastMessage

---

test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/UnitTests/Common/UtilityFacts.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/UnitTests/Connections/ConnectionStateFacts.js

Fix verifyLastActive tests broken by Chrome timer throttling fix

---

src/Microsoft.AspNet.SignalR.JS/.eslintrc.js
src/Microsoft.AspNet.SignalR.JS/build.ps1
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.JS/package.json

Fixes https://github.com/SignalR/SignalR/issues/4361
Didn't add the no-extra-parens rule referenced in the issues because, a. it is a warning not an error, b. applying it seems like it broke if statements of the sort `if (something || (anotherthing && thirdthing))`. Turned it into `if (something || anotherthing && thirdthing)` which seems wrong.

Enable ESLint

---

.vsts-pipelines/templates/signalr-build.yml

We are migrating all repositories to 1ES hosted pools. The functionality stays the same but we have to update the yamls.
Tracking issue: https://github.com/dotnet/core-eng/issues/14276
/cc: @jonfortescue

Migrate to 1ES hosted pools
