SignalR/SignalR

src/Microsoft.AspNet.SignalR.Core/Hubs/TypedClientBuilder.cs
tests/Microsoft.AspNet.SignalR.Tests/Server/Hubs/TypedClientBuilderFacts.cs

Enabling generic parameters on methods of interfaces used to define strongly named hubs
#3594

Jhmt master

---

build/Build.proj
nuspecs/Microsoft.AspNet.SignalR.Client.nuspec
src/Microsoft.AspNet.SignalR.Client.Store/Microsoft.AspNet.SignalR.Client.Store.csproj
src/Microsoft.AspNet.SignalR.Client.Store/Transports/WebSocketTransport.cs
src/Microsoft.AspNet.SignalR.Client.Store/packages.config
src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.Client/Transports/AutoTransport.cs
tests/Microsoft.AspNet.SignalR.Client.Store.Tests/Fakes/FakeConnection.cs
tests/Microsoft.AspNet.SignalR.Client.Store.Tests/FunctionalTests/EndToEndTests.cs
tests/Microsoft.AspNet.SignalR.Client.Store.Tests/Microsoft.AspNet.SignalR.Client.Store.Tests.csproj
tests/Microsoft.AspNet.SignalR.Client.Store.Tests/Transports/WebSocketTransportFacts.cs

Creating a dedicated SignalR store client

IndependenceDay

---

CONTRIBUTING.md
src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.foreverFrame.js
src/Microsoft.AspNet.SignalR.Client.JS/jquery.signalR.transports.longPolling.js
src/Microsoft.AspNet.SignalR.Core/IRequest.cs
src/Microsoft.AspNet.SignalR.SqlServer/ObservableDbOperation.cs
tests/Microsoft.AspNet.SignalR.Client.JS.Tests/Build/test.config.js

I'm presuming the msopentech.com link for the Contributor License Agreement doesn't work anymore because of the [merge with Microsoft](https://msopentech.com/blog/2015/04/17/nextchapter/).

Fixed the CLA link in Contributing.md and some additional typos

---

src/Microsoft.AspNet.SignalR.Redis/RedisConnection.cs

Fixing script to not fail on reconnect when the key does not exist

---

src/Microsoft.AspNet.SignalR.Redis/RedisMessageBus.cs

Because SignalR executes Redis scripts and uses Redis subscryptions it receives ConnectionFailed/ConnectionRestored events twice - once for ConnectionType.Interactive and once for ConnectionType.Subscription. This change prevents from running a subsequent event if the previous event completed successfully.
Fixes #3729

Preventing from running connection event handlers twice

---

src/Microsoft.AspNet.SignalR.Redis/Microsoft.AspNet.SignalR.Redis.csproj
src/Microsoft.AspNet.SignalR.Redis/RedisConnection.cs
src/Microsoft.AspNet.SignalR.Redis/RedisMessageBus.cs
src/Microsoft.AspNet.SignalR.Redis/TraceTextWriter.cs

also: add some tracing to redis message bus code
fixes #3093

fix #3093 by cleaning up Redis connection state

---

src/Microsoft.AspNet.SignalR.Core/Hubs/HubDispatcher.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/MessageBus.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutMessageBus.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStream.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutSubscription.cs
src/Microsoft.AspNet.SignalR.Core/Transports/ForeverTransport.cs
src/Microsoft.AspNet.SignalR.Core/Transports/ServerSentEventsTransport.cs
src/Microsoft.AspNet.SignalR.Core/Transports/WebSocketTransport.cs

Adding additional logging for Scaleout and transports

---

src/Microsoft.AspNet.SignalR.ServiceBus3/Microsoft.AspNet.SignalR.ServiceBus3.csproj

Target net45 in ServiceBus3

---

src/Microsoft.AspNet.SignalR.Crank/CrankArguments.cs
src/Microsoft.AspNet.SignalR.Crank/DefaultConnectionFactory.cs

Feature #4020

---

src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutStream.cs

use EDI to capture exceptions in ScaleoutStream

---

samples/Microsoft.AspNet.SignalR.Samples/Web.config
src/Microsoft.AspNet.SignalR.Core/Messaging/MessageBus.cs
src/Microsoft.AspNet.SignalR.Core/Messaging/ScaleoutSubscription.cs
src/Microsoft.AspNet.SignalR.Redis/RedisMessageBus.cs

This reverts the previous three commits to `dev` which added extra tracing. It was too noisy. I'll manually merge this.

remove extra traces, they're too noisy

---

Directory.Build.props
src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.csproj
src/Microsoft.AspNet.SignalR.JS/build.ps1
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.version.js
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Connections/FarmFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/HostedTest.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/HostedTestFactory.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/TracingTestHost.cs
test/Microsoft.AspNet.SignalR.Tests.Common/TestTraceManager.cs

Also:
* Embed the version number in the JS file
* Disable logging from .NET functional tests by default.

NuGet Metadata Updates and more

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js

Fix: synchronous XMLHttpRequest.

---

build/arcade.props
build/prepare-symbols.ps1
build/repo.targets

This is part of getting the symbols up on to the symbol server in the new build system.
Going to merge once the CI is green since there's other stuff blocked on getting this in.

generate windows PDBs as part of the build

---

src/Microsoft.AspNet.SignalR.JS/LICENSE.md
src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.csproj
src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.nuspec
src/Microsoft.AspNet.SignalR.JS/README.md
src/Microsoft.AspNet.SignalR.JS/build.ps1
src/Microsoft.AspNet.SignalR.JS/pack.ps1
src/Microsoft.AspNet.SignalR.JS/package.json

fixes #4212 by putting the npm package build in this repo
TODO:

Build the npm package in this repo

---

.vsts-pipelines/builds/ci-official.yml
.vsts-pipelines/templates/signalr-build.yml

Publishes symbols to a share as part of the build (to be later released to symbol server)

Publish Symbols as part of build

---

src/Microsoft.AspNet.SignalR.Client/Infrastructure/TransportInitializationHandler.cs

fixes #3722
If `Disconnect` is called while `Start` is still running, we cancel and then immediately dispose the CTS backing `_disconnectToken`. In .NET 4.5, this causes `Register` to throw an ObjectDisposedException. In .NET 4.6 and higher (and .NET Core) this does not throw an ODE.
Since we only dispose immediately after cancelling, we can treat the ODE like cancelation.

fix #3722 by catching ODE when registering to CTS

---

build/loc/SatellitePackage.csproj
build/repo.targets
src/Microsoft.AspNet.SignalR.Client/loc/Microsoft.AspNet.SignalR.Client.satellite.nuspec
src/Microsoft.AspNet.SignalR.Core/loc/Microsoft.AspNet.SignalR.Core.satellite.nuspec
src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.csproj
src/Microsoft.AspNet.SignalR.JS/Microsoft.AspNet.SignalR.JS.nuspec
src/Microsoft.AspNet.SignalR.Redis/loc/Microsoft.AspNet.SignalR.Redis.satellite.nuspec
src/Microsoft.AspNet.SignalR.ServiceBus/loc/Microsoft.AspNet.SignalR.ServiceBus.satellite.nuspec
src/Microsoft.AspNet.SignalR.ServiceBus3/loc/Microsoft.AspNet.SignalR.ServiceBus3.satellite.nuspec
src/Microsoft.AspNet.SignalR.SqlServer/loc/Microsoft.AspNet.SignalR.SqlServer.satellite.nuspec
src/Microsoft.AspNet.SignalR.SystemWeb/loc/Microsoft.AspNet.SignalR.SystemWeb.satellite.nuspec
src/Microsoft.AspNet.SignalR/loc/Microsoft.AspNet.SignalR.satellite.nuspec
version.props

The copyright notices for some of the packages were wrong and had to be corrected during publishing :)

fix package metadata

---

build/loc/LocalizeDlls.targets
build/loc/lsbuild.proj

Worked some MSBuild magic to speed up builds.

Run localization in parallel for faster builds

---

src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.Client/Infrastructure/UrlBuilder.cs
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/Microsoft.AspNet.SignalR.Client.JS.Tests.csproj
test/Microsoft.AspNet.SignalR.Client.JS.Tests/karma.conf.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Core/NegotiateFacts.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Core/RedirectFacts.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Transports/ForeverFrame/FFConnectFacts.js
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/NegotiateFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/App_Start/Initializer.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Hubs/RedirectTestHub.cs

 Support query string for RedirectUrl for JS and C# client

---

src/Microsoft.AspNet.SignalR.Client/Hubs/HubProxy.cs

Make HubProxy state more thread-safe

---

src/Microsoft.AspNet.SignalR.Client/Connection.cs
src/Microsoft.AspNet.SignalR.JS/jquery.signalR.core.js
test/Microsoft.AspNet.SignalR.Client.JS.Tests/wwwroot/Tests/FunctionalTests/Core/RedirectFacts.js
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/NegotiateFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/App_Start/Initializer.cs

Bump the 2.4.1 C# and JS client's clientProtocol from 2.0 to 2.1

---

src/Microsoft.AspNet.SignalR.Client/Transports/WebSocketTransport.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Client/HubProxyFacts.cs
test/Microsoft.AspNet.SignalR.FunctionalTests/Server/Transports/WebSocketFacts.cs
test/Microsoft.AspNet.SignalR.Tests.Common/Infrastructure/OwinTestHost.cs

Avoid multiple simultanious DoReconnect loops

---

src/Microsoft.AspNet.SignalR.Client/Transports/WebSocketTransport.cs

- Exit early for OperationCanceledExceptions and aborted requests.

Catch all exceptions in WebSocketTransport.DoReconnect

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js

Use fetch in beforeunload

---

.config/CredScanSuppressions.json

Suppress credscan error for test .pfx file

Add suppression for .pfx file

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.transports.common.js

TODO: Add tests once #4603 is merged
Addresses #4567

Abort with credentials

---

.vsts-pipelines/templates/signalr-build.yml
eng/common/generate-sbom-prep.ps1
eng/common/generate-sbom-prep.sh
eng/common/retain-build.ps1
eng/common/templates/steps/generate-sbom.yml
eng/common/templates/steps/retain-build.yml

Part of https://github.com/dotnet/arcade/issues/8477

Add SBom generation

---

.vsts-pipelines/builds/ci-official.yml
.vsts-pipelines/templates/signalr-build.yml

Should have tested after adding the check...
But we now get a nice radio button in AzDo!

Fix FinalBuild variable

---

.vsts-pipelines/templates/signalr-build.yml

+@dougbu
Wouldn't let me add you as a reviewer :/

Update public pool name

---

.vsts-pipelines/templates/signalr-build.yml

Switch to new build images per https://github.com/dotnet/arcade/issues/9592.

Switch to new build images

---

src/Microsoft.AspNet.SignalR.JS/jquery.signalR.hubs.js

Fix for the bug introduced in #4249 ,
also mentioned in #4386.

fix hub.off function has a wrong "unsubscription"

---

.vsts-pipelines/templates/signalr-build.yml

Use -Svc pools from here on out
